const mongoose = require("mongoose");

const vacancySchema = new mongoose.Schema(
  {
    vacancy_id: String,
    title: String,
    grade: String,
    date_posted: String,
    deadline: String,
    department: String,
    county: String,
    active: Boolean,
    ny_help: String,
    agency: String,
    occupational_category: String,
    salary_grade: String,
    bargaining_unit: String,
    salary_range: String,
    employment_type: String,
    appointment_type: String,
    jurisdictional_class: String,
    travel_percentage: String,
    workweek: String,
    hours_per_week: String,
    from: String,
    to: String,
    flextime_allowed: String,
    mandatory_overtime: String,
    compressed_workweek_allowed: String,
    telecommuting_allowed: String,
    street_address: String,
    street_2: String,
    city: String,
    state: String,
    zip_code: String,
    duties_description: String,
    minimum_qualifications: String,
    additional_comments: String,
    name: String,
    telephone: String,
    fax: String,
    email_address: String,
    street: String,
    notes_on_applying: String,
    macroArea: String,
    nyRegion: String,
    educationalRequirements: String,
    workExperienceRequirements: String,
    salaryRange: String,
  },
  { strict: false }
);

module.exports = mongoose.model("Vacancy", vacancySchema);
